[DB]
    #DSN = "host=127.0.0.1 port=5432 user=postgres password=postgres dbname=postgres sslmode=disable"
    DSN = "postgres://postgres:postgres@127.0.0.1/postgres?sslmode=disable"

[Setting]
    Port = "8080"