name: build CI

on: [pull_request, push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: set up GO
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Build
        run: go build -o deploy/main
      - name: copy
        run: cp ./Procfile ./deploy
      - name: ls
        run: ls
      - shell: bash
        env:
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
        run: |
          cd deploy
          git init
          git config user.name "Heroku-Deploy"
          git config user.email "$HEROKU_EMAIL"
          git add . && git commit -m init
      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          dontautocreate: true
          
