name: build CI

on: [pull_request, push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: set up GO
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Build
        run: go build -o deploy/main
      - name: ls
        run: |
          cp ./Dockerfile ./deploy
          ls ./deploy
      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          dontautocreate: true
          usedocker: true
          appdir: deploy
          
