name: docker CI

on: [pull_request, push]

jobs:
  docker:

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker Image
        run: docker build -t app .
    
          
